// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server_DB_Postgres;

#nullable disable

namespace Server_DB_Postgres.Migrations
{
    [DbContext(typeof(DbContextGame))]
    [Migration("20251218141532_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.BaseEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Damage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("damage");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type_id");

                    b.Property<bool>("IsUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.HasKey("Id")
                        .HasName("base_equipments__pkey");

                    b.HasIndex("EquipmentTypeId")
                        .HasDatabaseName("base_equipments__equipment_type_id__idx");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("base_equipments__name__idx");

                    b.ToTable("base_equipments", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.BaseHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("damage");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("health");

                    b.Property<bool>("IsUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique");

                    b.Property<int>("MainStat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("main_stat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.HasKey("Id")
                        .HasName("base_heroes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("base_heroes__name__idx");

                    b.ToTable("base_heroes", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.CreatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("creature_types__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("creature_types__name__idx");

                    b.ToTable("creature_types", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.DamageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DevHintRu")
                        .HasColumnType("text")
                        .HasColumnName("dev_hint_ru");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("damage_types__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("damage_types__name__idx");

                    b.ToTable("damage_types", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attack")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attack");

                    b.Property<bool>("CanCraftJewelcrafting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_craft_jewelcrafting");

                    b.Property<bool>("CanCraftSmithing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_craft_smithing");

                    b.Property<int>("MassMagical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mass_magical");

                    b.Property<int>("MassPhysical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mass_physical");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.Property<int>("SlotTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type_id");

                    b.Property<int>("SpendActionPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("spend_action_points");

                    b.HasKey("Id")
                        .HasName("equipment_types__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("equipment_types__name__idx");

                    b.HasIndex("SlotTypeId")
                        .HasDatabaseName("equipment_types__slot_type_id__idx");

                    b.ToTable("equipment_types", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.MaterialDamagePercent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("damage_type_id");

                    b.Property<int>("Percent")
                        .HasColumnType("integer")
                        .HasColumnName("percent");

                    b.Property<int>("SmithingMaterialsId")
                        .HasColumnType("integer")
                        .HasColumnName("smithing_materials_id");

                    b.HasKey("Id")
                        .HasName("material_damage_percents__pkey");

                    b.HasIndex("DamageTypeId")
                        .HasDatabaseName("material_damage_percents__damage_type_id__idx");

                    b.HasIndex("SmithingMaterialsId")
                        .HasDatabaseName("material_damage_percents__smithing_materials_id__idx");

                    b.ToTable("material_damage_percents", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.SlotType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("slot_types__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("slot_types__name__idx");

                    b.ToTable("slot_types", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.SmithingMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("smithing_materials__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("smithing_materials__name__idx");

                    b.ToTable("smithing_materials", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.X_EquipmentType_DamageType", b =>
                {
                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type_id")
                        .HasColumnOrder(0);

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("damage_type_id")
                        .HasColumnOrder(1);

                    b.Property<int>("DamageCoef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("damage_coef");

                    b.HasKey("EquipmentTypeId", "DamageTypeId")
                        .HasName("x_equipment_type_damage_type__pkey");

                    b.HasIndex("DamageTypeId")
                        .HasDatabaseName("x_equipment_type_damage_type__damage_type_id__idx");

                    b.ToTable("x_equipment_type_damage_type", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.X_Hero_CreatureType", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("integer")
                        .HasColumnName("hero_id")
                        .HasColumnOrder(0);

                    b.Property<int>("CreatureTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_type_id")
                        .HasColumnOrder(1);

                    b.HasKey("HeroId", "CreatureTypeId")
                        .HasName("x_hero_creature_type__pkey");

                    b.HasIndex("CreatureTypeId")
                        .HasDatabaseName("x_hero_creature_type__creature_type_id__idx");

                    b.ToTable("x_hero_creature_type", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Logs.UserAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("user_authorizations__pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("user_authorizations__user_id__idx");

                    b.ToTable("user_authorizations", "logs");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Server.UserBanReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("user_ban_reasons__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("user_ban_reasons__name__idx");

                    b.ToTable("user_ban_reasons", "server");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("users__pkey");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users__email__idx");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserBanReasonId")
                        .HasColumnType("integer")
                        .HasColumnName("user_ban_reason_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("user_bans__pkey");

                    b.HasIndex("UserBanReasonId")
                        .HasDatabaseName("user_bans__user_ban_reason_id__idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("user_bans__user_id__idx");

                    b.ToTable("user_bans", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.BaseEquipment", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.EquipmentType", "EquipmentTypes")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("base_equipments__equipment_type_id__equipment_types__fkey");

                    b.Navigation("EquipmentTypes");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.EquipmentType", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.SlotType", null)
                        .WithMany("EquipmentTypes")
                        .HasForeignKey("SlotTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("equipment_types__slot_type_id__slot_types__fkey");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.MaterialDamagePercent", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.DamageType", "DamageType")
                        .WithMany()
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("material_damage_percents__damage_type_id__damage_types__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.GameData.SmithingMaterial", "SmithingMaterials")
                        .WithMany("MaterialDamagePercents")
                        .HasForeignKey("SmithingMaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("material_damage_percents__smithing_materials_id__smithing_materials__fkey");

                    b.Navigation("DamageType");

                    b.Navigation("SmithingMaterials");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.X_EquipmentType_DamageType", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.DamageType", "DamageType")
                        .WithMany("X_EquipmentType_DamageType")
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("x_equipment_type_damage_type__damage_type_id__damage_types__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.GameData.EquipmentType", "EquipmentType")
                        .WithMany("X_EquipmentType_DamageType")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("x_equipment_type_damage_type__equipment_type_id__equipment_types__fkey");

                    b.Navigation("DamageType");

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.X_Hero_CreatureType", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.CreatureType", "CreatureTypes")
                        .WithMany("X_Hero_CreatureType")
                        .HasForeignKey("CreatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("x_hero_creature_type__creature_type_id__creature_types__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.GameData.BaseHero", "BaseHero")
                        .WithMany("X_Hero_CreatureType")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("x_hero_creature_type__hero_id__base_heroes__fkey");

                    b.Navigation("BaseHero");

                    b.Navigation("CreatureTypes");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Logs.UserAuthorization", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_authorizations__user_id__users__fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserBan", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Server.UserBanReason", "UserBanReason")
                        .WithMany("UserBans")
                        .HasForeignKey("UserBanReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_bans__user_ban_reason_id__user_ban_reasons__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "User")
                        .WithMany("UserBans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_bans__user_id__users__fkey");

                    b.Navigation("User");

                    b.Navigation("UserBanReason");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.BaseHero", b =>
                {
                    b.Navigation("X_Hero_CreatureType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.CreatureType", b =>
                {
                    b.Navigation("X_Hero_CreatureType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.DamageType", b =>
                {
                    b.Navigation("X_EquipmentType_DamageType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.EquipmentType", b =>
                {
                    b.Navigation("X_EquipmentType_DamageType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.SlotType", b =>
                {
                    b.Navigation("EquipmentTypes");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.SmithingMaterial", b =>
                {
                    b.Navigation("MaterialDamagePercents");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Server.UserBanReason", b =>
                {
                    b.Navigation("UserBans");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.User", b =>
                {
                    b.Navigation("UserBans");
                });
#pragma warning restore 612, 618
        }
    }
}
