// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server_DB_Postgres;

#nullable disable

namespace Server_DB_Postgres.Migrations
{
    [DbContext(typeof(DbContext_Game))]
    [Migration("20251221062947_Fix8")]
    partial class Fix8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server_DB_Postgres.Entities.Collection.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseEquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("base_equipment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("equipments__pkey");

                    b.HasIndex("BaseEquipmentId")
                        .HasDatabaseName("equipments__base_equipment_id__idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("equipments__user_id__idx");

                    b.ToTable("equipments", "collection");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Collection.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Agility")
                        .HasColumnType("integer")
                        .HasColumnName("agility");

                    b.Property<long>("Attack")
                        .HasColumnType("bigint")
                        .HasColumnName("attack");

                    b.Property<int>("BaseHeroId")
                        .HasColumnType("integer")
                        .HasColumnName("base_hero_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CritChance")
                        .HasColumnType("integer")
                        .HasColumnName("crit_chance");

                    b.Property<int>("CritPower")
                        .HasColumnType("integer")
                        .HasColumnName("crit_power");

                    b.Property<int>("EnduranceMagical")
                        .HasColumnType("integer")
                        .HasColumnName("endurance_magical");

                    b.Property<int>("EndurancePhysical")
                        .HasColumnType("integer")
                        .HasColumnName("endurance_physical");

                    b.Property<Guid?>("Equipment10Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment10id");

                    b.Property<Guid?>("Equipment11Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment11id");

                    b.Property<Guid?>("Equipment12Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment12id");

                    b.Property<Guid?>("Equipment13Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment13id");

                    b.Property<Guid?>("Equipment14Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment14id");

                    b.Property<Guid?>("Equipment15Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment15id");

                    b.Property<Guid?>("Equipment16Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment16id");

                    b.Property<Guid?>("Equipment17Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment17id");

                    b.Property<Guid?>("Equipment18Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment18id");

                    b.Property<Guid?>("Equipment19Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment19id");

                    b.Property<Guid?>("Equipment1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment1id");

                    b.Property<Guid?>("Equipment20Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment20id");

                    b.Property<Guid?>("Equipment21Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment21id");

                    b.Property<Guid?>("Equipment22Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment22id");

                    b.Property<Guid?>("Equipment23Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment23id");

                    b.Property<Guid?>("Equipment24Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment24id");

                    b.Property<Guid?>("Equipment2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment2id");

                    b.Property<Guid?>("Equipment3Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment3id");

                    b.Property<Guid?>("Equipment4Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment4id");

                    b.Property<Guid?>("Equipment5Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment5id");

                    b.Property<Guid?>("Equipment6Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment6id");

                    b.Property<Guid?>("Equipment7Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment7id");

                    b.Property<Guid?>("Equipment8Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment8id");

                    b.Property<Guid?>("Equipment9Id")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment9id");

                    b.Property<long>("ExperienceNow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("experience_now");

                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("group_name");

                    b.Property<int>("Haste")
                        .HasColumnType("integer")
                        .HasColumnName("haste");

                    b.Property<long>("Health")
                        .HasColumnType("bigint")
                        .HasColumnName("health");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer")
                        .HasColumnName("intelligence");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<int>("Rarity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("rarity");

                    b.Property<int>("ResistDamageMagical")
                        .HasColumnType("integer")
                        .HasColumnName("resist_damage_magical");

                    b.Property<int>("ResistDamagePhysical")
                        .HasColumnType("integer")
                        .HasColumnName("resist_damage_physical");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Versality")
                        .HasColumnType("integer")
                        .HasColumnName("versality");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("heroes__pkey");

                    b.HasIndex("BaseHeroId")
                        .HasDatabaseName("heroes__base_hero_id__idx");

                    b.HasIndex("Equipment10Id")
                        .HasDatabaseName("heroes__equipment10id__idx");

                    b.HasIndex("Equipment11Id")
                        .HasDatabaseName("heroes__equipment11id__idx");

                    b.HasIndex("Equipment12Id")
                        .HasDatabaseName("heroes__equipment12id__idx");

                    b.HasIndex("Equipment13Id")
                        .HasDatabaseName("heroes__equipment13id__idx");

                    b.HasIndex("Equipment14Id")
                        .HasDatabaseName("heroes__equipment14id__idx");

                    b.HasIndex("Equipment15Id")
                        .HasDatabaseName("heroes__equipment15id__idx");

                    b.HasIndex("Equipment16Id")
                        .HasDatabaseName("heroes__equipment16id__idx");

                    b.HasIndex("Equipment17Id")
                        .HasDatabaseName("heroes__equipment17id__idx");

                    b.HasIndex("Equipment18Id")
                        .HasDatabaseName("heroes__equipment18id__idx");

                    b.HasIndex("Equipment19Id")
                        .HasDatabaseName("heroes__equipment19id__idx");

                    b.HasIndex("Equipment1Id")
                        .HasDatabaseName("heroes__equipment1id__idx");

                    b.HasIndex("Equipment20Id")
                        .HasDatabaseName("heroes__equipment20id__idx");

                    b.HasIndex("Equipment21Id")
                        .HasDatabaseName("heroes__equipment21id__idx");

                    b.HasIndex("Equipment22Id")
                        .HasDatabaseName("heroes__equipment22id__idx");

                    b.HasIndex("Equipment23Id")
                        .HasDatabaseName("heroes__equipment23id__idx");

                    b.HasIndex("Equipment24Id")
                        .HasDatabaseName("heroes__equipment24id__idx");

                    b.HasIndex("Equipment2Id")
                        .HasDatabaseName("heroes__equipment2id__idx");

                    b.HasIndex("Equipment3Id")
                        .HasDatabaseName("heroes__equipment3id__idx");

                    b.HasIndex("Equipment4Id")
                        .HasDatabaseName("heroes__equipment4id__idx");

                    b.HasIndex("Equipment5Id")
                        .HasDatabaseName("heroes__equipment5id__idx");

                    b.HasIndex("Equipment6Id")
                        .HasDatabaseName("heroes__equipment6id__idx");

                    b.HasIndex("Equipment7Id")
                        .HasDatabaseName("heroes__equipment7id__idx");

                    b.HasIndex("Equipment8Id")
                        .HasDatabaseName("heroes__equipment8id__idx");

                    b.HasIndex("Equipment9Id")
                        .HasDatabaseName("heroes__equipment9id__idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("heroes__user_id__idx");

                    b.ToTable("heroes", "collection");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.BaseEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Damage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("damage");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type_id");

                    b.Property<string>("Health")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("health");

                    b.Property<bool>("IsUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.HasKey("Id")
                        .HasName("base_equipments__pkey");

                    b.HasIndex("EquipmentTypeId")
                        .HasDatabaseName("base_equipments__equipment_type_id__idx");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("base_equipments__name__idx");

                    b.ToTable("base_equipments", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.BaseHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("damage");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("health");

                    b.Property<bool>("IsUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique");

                    b.Property<int>("MainStat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("main_stat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.HasKey("Id")
                        .HasName("base_heroes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("base_heroes__name__idx");

                    b.ToTable("base_heroes", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.CreatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("creature_types__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("creature_types__name__idx");

                    b.ToTable("creature_types", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.DamageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DevHintRu")
                        .HasColumnType("text")
                        .HasColumnName("dev_hint_ru");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("damage_types__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("damage_types__name__idx");

                    b.ToTable("damage_types", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attack")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attack");

                    b.Property<bool?>("BlockOtherHand")
                        .HasColumnType("boolean")
                        .HasColumnName("block_other_hand");

                    b.Property<bool>("CanCraftJewelcrafting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_craft_jewelcrafting");

                    b.Property<bool>("CanCraftSmithing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_craft_smithing");

                    b.Property<int>("MassMagical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mass_magical");

                    b.Property<int>("MassPhysical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mass_physical");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.Property<int>("SlotTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type_id");

                    b.Property<int>("SpendActionPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("spend_action_points");

                    b.HasKey("Id")
                        .HasName("equipment_types__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("equipment_types__name__idx");

                    b.HasIndex("SlotTypeId")
                        .HasDatabaseName("equipment_types__slot_type_id__idx");

                    b.ToTable("equipment_types", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.MaterialDamagePercent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("damage_type_id");

                    b.Property<int>("Percent")
                        .HasColumnType("integer")
                        .HasColumnName("percent");

                    b.Property<int>("SmithingMaterialsId")
                        .HasColumnType("integer")
                        .HasColumnName("smithing_materials_id");

                    b.HasKey("Id")
                        .HasName("material_damage_percents__pkey");

                    b.HasIndex("DamageTypeId")
                        .HasDatabaseName("material_damage_percents__damage_type_id__idx");

                    b.HasIndex("SmithingMaterialsId")
                        .HasDatabaseName("material_damage_percents__smithing_materials_id__idx");

                    b.ToTable("material_damage_percents", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.SlotType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("slot_types__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("slot_types__name__idx");

                    b.ToTable("slot_types", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.SmithingMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("smithing_materials__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("smithing_materials__name__idx");

                    b.ToTable("smithing_materials", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.X_EquipmentType_DamageType", b =>
                {
                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type_id")
                        .HasColumnOrder(0);

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("damage_type_id")
                        .HasColumnOrder(1);

                    b.Property<int>("DamageCoef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("damage_coef");

                    b.HasKey("EquipmentTypeId", "DamageTypeId")
                        .HasName("x_equipment_type_damage_type__pkey");

                    b.HasIndex("DamageTypeId")
                        .HasDatabaseName("x_equipment_type_damage_type__damage_type_id__idx");

                    b.ToTable("x_equipment_type_damage_type", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.X_Hero_CreatureType", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("integer")
                        .HasColumnName("hero_id")
                        .HasColumnOrder(0);

                    b.Property<int>("CreatureTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_type_id")
                        .HasColumnOrder(1);

                    b.HasKey("HeroId", "CreatureTypeId")
                        .HasName("x_hero_creature_type__pkey");

                    b.HasIndex("CreatureTypeId")
                        .HasDatabaseName("x_hero_creature_type__creature_type_id__idx");

                    b.ToTable("x_hero_creature_type", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Logs.UserAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<Guid?>("UserDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_device_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("user_authorizations__pkey");

                    b.HasIndex("UserDeviceId")
                        .HasDatabaseName("user_authorizations__user_device_id__idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("user_authorizations__user_id__idx");

                    b.ToTable("user_authorizations", "logs");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Server.UserBanReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("user_ban_reasons__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("user_ban_reasons__name__idx");

                    b.ToTable("user_ban_reasons", "server");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("users__pkey");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users__email__idx");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserBanReasonId")
                        .HasColumnType("integer")
                        .HasColumnName("user_ban_reason_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("user_bans__pkey");

                    b.HasIndex("UserBanReasonId")
                        .HasDatabaseName("user_bans__user_ban_reason_id__idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("user_bans__user_id__idx");

                    b.ToTable("user_bans", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_model");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_type");

                    b.Property<string>("DeviceUniqueIdentifier")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_unique_identifier");

                    b.Property<string>("GraphicsDeviceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("graphics_device_name");

                    b.Property<int?>("GraphicsMemorySize")
                        .HasColumnType("integer")
                        .HasColumnName("graphics_memory_size");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("operating_system");

                    b.Property<int?>("ProcessorCount")
                        .HasColumnType("integer")
                        .HasColumnName("processor_count");

                    b.Property<string>("ProcessorType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("processor_type");

                    b.Property<string>("SystemEnvironmentUserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("system_environment_user_name");

                    b.Property<string>("SystemInfoNpotSupport")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("system_info_npot_support");

                    b.Property<bool?>("SystemInfoSupportsInstancing")
                        .HasColumnType("boolean")
                        .HasColumnName("system_info_supports_instancing");

                    b.Property<int?>("SystemMemorySize")
                        .HasColumnType("integer")
                        .HasColumnName("system_memory_size");

                    b.Property<int?>("TimeZoneMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_zone_minutes");

                    b.HasKey("Id")
                        .HasName("user_devices__pkey");

                    b.ToTable("user_devices", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Collection.Equipment", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.BaseEquipment", "BaseEquipment")
                        .WithMany()
                        .HasForeignKey("BaseEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("equipments__base_equipment_id__base_equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("equipments__user_id__users__fkey");

                    b.Navigation("BaseEquipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Collection.Hero", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.BaseHero", "BaseHero")
                        .WithMany()
                        .HasForeignKey("BaseHeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("heroes__base_hero_id__base_heroes__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment10")
                        .WithMany()
                        .HasForeignKey("Equipment10Id")
                        .HasConstraintName("heroes__equipment10id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment11")
                        .WithMany()
                        .HasForeignKey("Equipment11Id")
                        .HasConstraintName("heroes__equipment11id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment12")
                        .WithMany()
                        .HasForeignKey("Equipment12Id")
                        .HasConstraintName("heroes__equipment12id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment13")
                        .WithMany()
                        .HasForeignKey("Equipment13Id")
                        .HasConstraintName("heroes__equipment13id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment14")
                        .WithMany()
                        .HasForeignKey("Equipment14Id")
                        .HasConstraintName("heroes__equipment14id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment15")
                        .WithMany()
                        .HasForeignKey("Equipment15Id")
                        .HasConstraintName("heroes__equipment15id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment16")
                        .WithMany()
                        .HasForeignKey("Equipment16Id")
                        .HasConstraintName("heroes__equipment16id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment17")
                        .WithMany()
                        .HasForeignKey("Equipment17Id")
                        .HasConstraintName("heroes__equipment17id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment18")
                        .WithMany()
                        .HasForeignKey("Equipment18Id")
                        .HasConstraintName("heroes__equipment18id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment19")
                        .WithMany()
                        .HasForeignKey("Equipment19Id")
                        .HasConstraintName("heroes__equipment19id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment1")
                        .WithMany()
                        .HasForeignKey("Equipment1Id")
                        .HasConstraintName("heroes__equipment1id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment20")
                        .WithMany()
                        .HasForeignKey("Equipment20Id")
                        .HasConstraintName("heroes__equipment20id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment21")
                        .WithMany()
                        .HasForeignKey("Equipment21Id")
                        .HasConstraintName("heroes__equipment21id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment22")
                        .WithMany()
                        .HasForeignKey("Equipment22Id")
                        .HasConstraintName("heroes__equipment22id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment23")
                        .WithMany()
                        .HasForeignKey("Equipment23Id")
                        .HasConstraintName("heroes__equipment23id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment24")
                        .WithMany()
                        .HasForeignKey("Equipment24Id")
                        .HasConstraintName("heroes__equipment24id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment2")
                        .WithMany()
                        .HasForeignKey("Equipment2Id")
                        .HasConstraintName("heroes__equipment2id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment3")
                        .WithMany()
                        .HasForeignKey("Equipment3Id")
                        .HasConstraintName("heroes__equipment3id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment4")
                        .WithMany()
                        .HasForeignKey("Equipment4Id")
                        .HasConstraintName("heroes__equipment4id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment5")
                        .WithMany()
                        .HasForeignKey("Equipment5Id")
                        .HasConstraintName("heroes__equipment5id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment6")
                        .WithMany()
                        .HasForeignKey("Equipment6Id")
                        .HasConstraintName("heroes__equipment6id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment7")
                        .WithMany()
                        .HasForeignKey("Equipment7Id")
                        .HasConstraintName("heroes__equipment7id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment8")
                        .WithMany()
                        .HasForeignKey("Equipment8Id")
                        .HasConstraintName("heroes__equipment8id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Equipment", "Equipment9")
                        .WithMany()
                        .HasForeignKey("Equipment9Id")
                        .HasConstraintName("heroes__equipment9id__equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("heroes__user_id__users__fkey");

                    b.Navigation("BaseHero");

                    b.Navigation("Equipment1");

                    b.Navigation("Equipment10");

                    b.Navigation("Equipment11");

                    b.Navigation("Equipment12");

                    b.Navigation("Equipment13");

                    b.Navigation("Equipment14");

                    b.Navigation("Equipment15");

                    b.Navigation("Equipment16");

                    b.Navigation("Equipment17");

                    b.Navigation("Equipment18");

                    b.Navigation("Equipment19");

                    b.Navigation("Equipment2");

                    b.Navigation("Equipment20");

                    b.Navigation("Equipment21");

                    b.Navigation("Equipment22");

                    b.Navigation("Equipment23");

                    b.Navigation("Equipment24");

                    b.Navigation("Equipment3");

                    b.Navigation("Equipment4");

                    b.Navigation("Equipment5");

                    b.Navigation("Equipment6");

                    b.Navigation("Equipment7");

                    b.Navigation("Equipment8");

                    b.Navigation("Equipment9");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.BaseEquipment", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.EquipmentType", "EquipmentTypes")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("base_equipments__equipment_type_id__equipment_types__fkey");

                    b.Navigation("EquipmentTypes");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.EquipmentType", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.SlotType", null)
                        .WithMany("EquipmentTypes")
                        .HasForeignKey("SlotTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("equipment_types__slot_type_id__slot_types__fkey");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.MaterialDamagePercent", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.DamageType", "DamageType")
                        .WithMany()
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("material_damage_percents__damage_type_id__damage_types__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.GameData.SmithingMaterial", "SmithingMaterials")
                        .WithMany("MaterialDamagePercents")
                        .HasForeignKey("SmithingMaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("material_damage_percents__smithing_materials_id__smithing_materials__fkey");

                    b.Navigation("DamageType");

                    b.Navigation("SmithingMaterials");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.X_EquipmentType_DamageType", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.DamageType", "DamageType")
                        .WithMany("X_EquipmentType_DamageType")
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("x_equipment_type_damage_type__damage_type_id__damage_types__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.GameData.EquipmentType", "EquipmentType")
                        .WithMany("X_EquipmentType_DamageType")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("x_equipment_type_damage_type__equipment_type_id__equipment_types__fkey");

                    b.Navigation("DamageType");

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.X_Hero_CreatureType", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.CreatureType", "CreatureTypes")
                        .WithMany("X_Hero_CreatureType")
                        .HasForeignKey("CreatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("x_hero_creature_type__creature_type_id__creature_types__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.GameData.BaseHero", "BaseHero")
                        .WithMany("X_Hero_CreatureType")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("x_hero_creature_type__hero_id__base_heroes__fkey");

                    b.Navigation("BaseHero");

                    b.Navigation("CreatureTypes");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Logs.UserAuthorization", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.UserDevice", "UserDevice")
                        .WithMany()
                        .HasForeignKey("UserDeviceId")
                        .HasConstraintName("user_authorizations__user_device_id__user_devices__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_authorizations__user_id__users__fkey");

                    b.Navigation("User");

                    b.Navigation("UserDevice");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserBan", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Server.UserBanReason", "UserBanReason")
                        .WithMany("UserBans")
                        .HasForeignKey("UserBanReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_bans__user_ban_reason_id__user_ban_reasons__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "User")
                        .WithMany("UserBans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_bans__user_id__users__fkey");

                    b.Navigation("User");

                    b.Navigation("UserBanReason");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.BaseHero", b =>
                {
                    b.Navigation("X_Hero_CreatureType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.CreatureType", b =>
                {
                    b.Navigation("X_Hero_CreatureType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.DamageType", b =>
                {
                    b.Navigation("X_EquipmentType_DamageType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.EquipmentType", b =>
                {
                    b.Navigation("X_EquipmentType_DamageType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.SlotType", b =>
                {
                    b.Navigation("EquipmentTypes");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.SmithingMaterial", b =>
                {
                    b.Navigation("MaterialDamagePercents");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Server.UserBanReason", b =>
                {
                    b.Navigation("UserBans");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.User", b =>
                {
                    b.Navigation("UserBans");
                });
#pragma warning restore 612, 618
        }
    }
}
