// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using General;
using General.DTO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server_DB_Postgres;

#nullable disable

namespace Server_DB_Postgres.Migrations
{
    [DbContext(typeof(DbContextGame))]
    [Migration("20260927141327_Migration_20260927_221306")]
    partial class Migration_20260927_221306
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("General.DTO.Entities.Collection.Equipment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("baseEquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("base_equipment_id");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("groupName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("group_name");

                    b.Property<Guid?>("heroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<int>("level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<int?>("slotId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_id");

                    b.Property<Dictionary<int, List<float>>>("stats")
                        .HasColumnType("jsonb")
                        .HasColumnName("stats");

                    b.Property<DateTimeOffset>("updatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("id")
                        .HasName("equipments__pkey");

                    b.HasIndex("baseEquipmentId")
                        .HasDatabaseName("equipments__base_equipment_id__idx");

                    b.HasIndex("heroId")
                        .HasDatabaseName("equipments__hero_id__idx");

                    b.HasIndex("slotId")
                        .HasDatabaseName("equipments__slot_id__idx");

                    b.HasIndex("userId")
                        .HasDatabaseName("equipments__user_id__idx");

                    b.HasIndex("heroId", "slotId")
                        .IsUnique()
                        .HasDatabaseName("equipments__hero_id__slot_id__idx")
                        .HasFilter("hero_id IS NOT NULL AND slot_id IS NOT NULL");

                    b.ToTable("equipments", "collection");
                });

            modelBuilder.Entity("General.DTO.Entities.Collection.Hero", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("agility")
                        .HasColumnType("real")
                        .HasColumnName("agility");

                    b.Property<int>("baseHeroId")
                        .HasColumnType("integer")
                        .HasColumnName("base_hero_id");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<float>("critChance")
                        .HasColumnType("real")
                        .HasColumnName("crit_chance");

                    b.Property<float>("critMultiplier")
                        .HasColumnType("real")
                        .HasColumnName("crit_multiplier");

                    b.Property<float>("damage")
                        .HasColumnType("real")
                        .HasColumnName("damage");

                    b.Property<float>("enduranceMagical")
                        .HasColumnType("real")
                        .HasColumnName("endurance_magical");

                    b.Property<float>("endurancePhysical")
                        .HasColumnType("real")
                        .HasColumnName("endurance_physical");

                    b.Property<float>("experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f)
                        .HasColumnName("experience");

                    b.Property<string>("groupName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("group_name");

                    b.Property<float>("haste")
                        .HasColumnType("real")
                        .HasColumnName("haste");

                    b.Property<float>("health")
                        .HasColumnType("real")
                        .HasColumnName("health");

                    b.Property<float>("initiative")
                        .HasColumnType("real")
                        .HasColumnName("initiative");

                    b.Property<float>("intelligence")
                        .HasColumnType("real")
                        .HasColumnName("intelligence");

                    b.Property<int>("level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<float>("strength")
                        .HasColumnType("real")
                        .HasColumnName("strength");

                    b.Property<DateTimeOffset>("updatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<float>("versality")
                        .HasColumnType("real")
                        .HasColumnName("versality");

                    b.Property<long>("version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("id")
                        .HasName("heroes__pkey");

                    b.HasIndex("baseHeroId")
                        .HasDatabaseName("heroes__base_hero_id__idx");

                    b.HasIndex("userId")
                        .HasDatabaseName("heroes__user_id__idx");

                    b.ToTable("heroes", "collection");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.Ability", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<int>("cooldown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cooldown");

                    b.Property<int>("cost")
                        .HasColumnType("integer")
                        .HasColumnName("cost");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("id")
                        .HasName("abilities__pkey");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("abilities__name__idx");

                    b.ToTable("abilities", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.BaseEquipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("equipmentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type_id");

                    b.Property<bool>("isUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Dictionary<EStatType, Dice>>("possibleStats")
                        .HasColumnType("jsonb")
                        .HasColumnName("possible_stats");

                    b.Property<int>("rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.Property<int?>("smithingMaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("smithing_material_id");

                    b.HasKey("id")
                        .HasName("base_equipments__pkey");

                    b.HasIndex("equipmentTypeId")
                        .HasDatabaseName("base_equipments__equipment_type_id__idx");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("base_equipments__name__idx");

                    b.HasIndex("smithingMaterialId")
                        .HasDatabaseName("base_equipments__smithing_material_id__idx");

                    b.ToTable("base_equipments", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.BaseHero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<Dice>("agility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("agility")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.Property<Dice>("critChance")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("crit_chance")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.Property<Dice>("critMultiplier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("crit_multiplier")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.Property<Dice>("damage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("damage")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.Property<Dice>("enduranceMagical")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("endurance_magical")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.Property<Dice>("endurancePhysical")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("endurance_physical")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.Property<Dice>("haste")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("haste")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.Property<Dice>("health")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("health")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.Property<Dice>("initiative")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("initiative")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.Property<Dice>("intelligence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("intelligence")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.Property<bool>("isPlayable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_playable");

                    b.Property<bool>("isUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique");

                    b.Property<int>("mainStat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("main_stat");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.Property<Dice>("strength")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("strength")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.Property<Dice>("versality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("versality")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.HasKey("id")
                        .HasName("base_heroes__pkey");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("base_heroes__name__idx");

                    b.ToTable("base_heroes", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.Battlefield", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("enumName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("enum_name");

                    b.Property<int>("maxEnemyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12)
                        .HasColumnName("max_enemy_count");

                    b.Property<int>("maxHeroCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12)
                        .HasColumnName("max_hero_count");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("id")
                        .HasName("battlefields__pkey");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("battlefields__name__idx");

                    b.ToTable("battlefields", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.CreatureType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("id")
                        .HasName("creature_types__pkey");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("creature_types__name__idx");

                    b.ToTable("creature_types", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.DamageType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("category");

                    b.Property<string>("devHintRu")
                        .HasColumnType("text")
                        .HasColumnName("dev_hint_ru");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("nameRu")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_ru");

                    b.HasKey("id")
                        .HasName("damage_types__pkey");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("damage_types__name__idx");

                    b.ToTable("damage_types", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.EquipmentType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool?>("blockOtherHand")
                        .HasColumnType("boolean")
                        .HasColumnName("block_other_hand");

                    b.Property<bool>("canCraftJewelcrafting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_craft_jewelcrafting");

                    b.Property<bool>("canCraftSmithing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_craft_smithing");

                    b.Property<Dice>("damage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("damage")
                        .HasDefaultValueSql("'{\"c\":0,\"s\":0}'::jsonb");

                    b.Property<int>("massMagical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mass_magical");

                    b.Property<int>("massPhysical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mass_physical");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("nameRu")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_ru");

                    b.Property<Dictionary<EStatType, Dice>>("possibleStats")
                        .HasColumnType("jsonb")
                        .HasColumnName("possible_stats");

                    b.Property<int>("slotTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type_id");

                    b.Property<int>("spendActionPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("spend_action_points");

                    b.HasKey("id")
                        .HasName("equipment_types__pkey");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("equipment_types__name__idx");

                    b.HasIndex("slotTypeId")
                        .HasDatabaseName("equipment_types__slot_type_id__idx");

                    b.ToTable("equipment_types", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.MaterialDamagePercent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("damageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("damage_type_id");

                    b.Property<int>("percent")
                        .HasColumnType("integer")
                        .HasColumnName("percent");

                    b.Property<int>("smithingMaterialsId")
                        .HasColumnType("integer")
                        .HasColumnName("smithing_materials_id");

                    b.HasKey("id")
                        .HasName("material_damage_percents__pkey");

                    b.HasIndex("damageTypeId")
                        .HasDatabaseName("material_damage_percents__damage_type_id__idx");

                    b.HasIndex("smithingMaterialsId")
                        .HasDatabaseName("material_damage_percents__smithing_materials_id__idx");

                    b.ToTable("material_damage_percents", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.Slot", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("mainSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("main_slot");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("slotTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type_id");

                    b.HasKey("id")
                        .HasName("slots__pkey");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("slots__name__idx");

                    b.HasIndex("slotTypeId")
                        .HasDatabaseName("slots__slot_type_id__idx");

                    b.ToTable("slots", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.SlotType", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("haveAltSlot")
                        .HasColumnType("boolean")
                        .HasColumnName("have_alt_slot");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("nameRu")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_ru");

                    b.Property<int>("sorting")
                        .HasColumnType("integer")
                        .HasColumnName("sorting");

                    b.HasKey("id")
                        .HasName("slot_types__pkey");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("slot_types__name__idx");

                    b.ToTable("slot_types", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.SmithingMaterial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("nameRu")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_ru");

                    b.HasKey("id")
                        .HasName("smithing_materials__pkey");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("smithing_materials__name__idx");

                    b.ToTable("smithing_materials", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.X_BaseHero_Ability", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("abilityId")
                        .HasColumnType("integer")
                        .HasColumnName("ability_id");

                    b.Property<int>("baseHeroId")
                        .HasColumnType("integer")
                        .HasColumnName("base_hero_id");

                    b.HasKey("id")
                        .HasName("x_base_heroes_abilities__pkey");

                    b.HasIndex("abilityId")
                        .HasDatabaseName("x_base_heroes_abilities__ability_id__idx");

                    b.HasIndex("baseHeroId", "abilityId")
                        .IsUnique()
                        .HasDatabaseName("x_base_heroes_abilities__base_hero_id__ability_id__idx");

                    b.ToTable("x_base_heroes_abilities", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.X_Battlefield_BaseHero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("baseHeroId")
                        .HasColumnType("integer")
                        .HasColumnName("base_hero_id");

                    b.Property<int>("battlefieldId")
                        .HasColumnType("integer")
                        .HasColumnName("battlefield_id");

                    b.Property<int>("count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("count");

                    b.Property<bool>("guarantSpawn")
                        .HasColumnType("boolean")
                        .HasColumnName("guarant_spawn");

                    b.Property<bool>("possibleRank")
                        .HasColumnType("boolean")
                        .HasColumnName("possible_rank");

                    b.Property<int>("probabilitySpawn")
                        .HasColumnType("integer")
                        .HasColumnName("probability_spawn");

                    b.HasKey("id")
                        .HasName("x_battlefields_base_heroes__pkey");

                    b.HasIndex("baseHeroId")
                        .HasDatabaseName("x_battlefields_base_heroes__base_hero_id__idx");

                    b.HasIndex("battlefieldId")
                        .HasDatabaseName("x_battlefields_base_heroes__battlefield_id__idx");

                    b.ToTable("x_battlefields_base_heroes", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.X_EquipmentType_DamageType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("damageCoef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("damage_coef");

                    b.Property<int>("damageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("damage_type_id");

                    b.Property<int>("equipmentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type_id");

                    b.HasKey("id")
                        .HasName("x_equipment_types_damage_types__pkey");

                    b.HasIndex("damageTypeId")
                        .HasDatabaseName("x_equipment_types_damage_types__damage_type_id__idx");

                    b.HasIndex("equipmentTypeId")
                        .HasDatabaseName("x_equipment_types_damage_types__equipment_type_id__idx");

                    b.ToTable("x_equipment_types_damage_types", "game_data");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.X_Hero_CreatureType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("baseHeroId")
                        .HasColumnType("integer")
                        .HasColumnName("base_hero_id");

                    b.Property<int>("creatureTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_type_id");

                    b.HasKey("id")
                        .HasName("x_heroes_creature_types__pkey");

                    b.HasIndex("baseHeroId")
                        .HasDatabaseName("x_heroes_creature_types__base_hero_id__idx");

                    b.HasIndex("creatureTypeId")
                        .HasDatabaseName("x_heroes_creature_types__creature_type_id__idx");

                    b.ToTable("x_heroes_creature_types", "game_data");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("identity_roles__pkey");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("identity_roles__normalized_name__idx");

                    b.ToTable("identity_roles", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("identity_role_claims__pkey");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("identity_role_claims__role_id__idx");

                    b.ToTable("identity_role_claims", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("identity_user_claims__pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("identity_user_claims__user_id__idx");

                    b.ToTable("identity_user_claims", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("identity_user_logins__pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("identity_user_logins__user_id__idx");

                    b.ToTable("identity_user_logins", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("identity_user_roles__pkey");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("identity_user_roles__role_id__idx");

                    b.ToTable("identity_user_roles", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("identity_user_tokens__pkey");

                    b.ToTable("identity_user_tokens", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Collection.DropRate", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<int[]>("counts")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("counts");

                    b.Property<int>("type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("id")
                        .HasName("drop_rates__pkey");

                    b.HasIndex("userId")
                        .HasDatabaseName("drop_rates__user_id__idx");

                    b.ToTable("drop_rates", "collection");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Logs.AuthenticationLog", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<IPAddress>("ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<bool>("success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<Guid?>("userDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_device_id");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("userSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_session_id");

                    b.Property<long>("version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("id")
                        .HasName("authentication_logs__pkey");

                    b.HasIndex("userDeviceId")
                        .HasDatabaseName("authentication_logs__user_device_id__idx");

                    b.HasIndex("userId")
                        .HasDatabaseName("authentication_logs__user_id__idx");

                    b.HasIndex("userSessionId")
                        .HasDatabaseName("authentication_logs__user_session_id__idx");

                    b.ToTable("authentication_logs", "logs");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Logs.RegistrationLog", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<IPAddress>("ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<bool>("success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<Guid?>("userDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_device_id");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("id")
                        .HasName("registration_logs__pkey");

                    b.HasIndex("userDeviceId")
                        .HasDatabaseName("registration_logs__user_device_id__idx");

                    b.HasIndex("userId")
                        .HasDatabaseName("registration_logs__user_id__idx");

                    b.ToTable("registration_logs", "logs");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Server.UserBanReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("user_ban_reasons__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("user_ban_reasons__name__idx");

                    b.ToTable("user_ban_reasons", "server");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Server.UserSessionInactivationReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("user_session_inactivation_reasons__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("user_session_inactivation_reasons__name__idx");

                    b.ToTable("user_session_inactivation_reasons", "server");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("time_zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("updatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("identity_users__pkey");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("identity_users__normalized_email__idx");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("identity_users__normalized_user_name__idx");

                    b.ToTable("identity_users", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserAccesskey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("DescriptorId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("descriptor_id");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_name");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<long>("SignatureCounter")
                        .HasColumnType("bigint")
                        .HasColumnName("signature_counter");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("updatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("user_accesskeys__pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("user_accesskeys__user_id__idx");

                    b.ToTable("user_accesskeys", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("UserBanReasonId")
                        .HasColumnType("integer")
                        .HasColumnName("user_ban_reason_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("updatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("user_bans__pkey");

                    b.HasIndex("UserBanReasonId")
                        .HasDatabaseName("user_bans__user_ban_reason_id__idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("user_bans__user_id__idx");

                    b.ToTable("user_bans", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_model");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_type");

                    b.Property<string>("DeviceUniqueIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_unique_identifier");

                    b.Property<string>("GraphicsDeviceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("graphics_device_name");

                    b.Property<int?>("GraphicsMemorySize")
                        .HasColumnType("integer")
                        .HasColumnName("graphics_memory_size");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operating_system");

                    b.Property<int?>("ProcessorCount")
                        .HasColumnType("integer")
                        .HasColumnName("processor_count");

                    b.Property<string>("ProcessorType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("processor_type");

                    b.Property<string>("SystemEnvironmentUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("system_environment_user_name");

                    b.Property<string>("SystemInfoNpotSupport")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("system_info_npot_support");

                    b.Property<bool?>("SystemInfoSupportsInstancing")
                        .HasColumnType("boolean")
                        .HasColumnName("system_info_supports_instancing");

                    b.Property<int?>("SystemMemorySize")
                        .HasColumnType("integer")
                        .HasColumnName("system_memory_size");

                    b.Property<int?>("TimeZoneMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_zone_minutes");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("user_devices__pkey");

                    b.ToTable("user_devices", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("InactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactivated_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<byte[]>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_hash");

                    b.Property<Guid>("UserDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_device_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("UserSessionInactivationReasonId")
                        .HasColumnType("integer")
                        .HasColumnName("user_session_inactivation_reason_id");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("updatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("user_sessions__pkey");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("user_sessions__refresh_token_hash__idx")
                        .HasFilter("is_used = false AND is_revoked = false");

                    b.HasIndex("UserDeviceId")
                        .HasDatabaseName("user_sessions__user_device_id__idx");

                    b.HasIndex("UserSessionInactivationReasonId")
                        .HasDatabaseName("user_sessions__user_session_inactivation_reason_id__idx");

                    b.ToTable("user_sessions", "users");
                });

            modelBuilder.Entity("General.DTO.Entities.Collection.Equipment", b =>
                {
                    b.HasOne("General.DTO.Entities.GameData.BaseEquipment", "baseEquipment")
                        .WithMany()
                        .HasForeignKey("baseEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("equipments__base_equipment_id__base_equipments__fkey");

                    b.HasOne("General.DTO.Entities.Collection.Hero", null)
                        .WithMany()
                        .HasForeignKey("heroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("equipments__hero_id__heroes__fkey");

                    b.HasOne("General.DTO.Entities.GameData.Slot", null)
                        .WithMany()
                        .HasForeignKey("slotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("equipments__slot_id__slots__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("equipments__user_id__identity_users__fkey");

                    b.Navigation("baseEquipment");
                });

            modelBuilder.Entity("General.DTO.Entities.Collection.Hero", b =>
                {
                    b.HasOne("General.DTO.Entities.GameData.BaseHero", "baseHero")
                        .WithMany()
                        .HasForeignKey("baseHeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("heroes__base_hero_id__base_heroes__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("heroes__user_id__identity_users__fkey");

                    b.Navigation("baseHero");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.BaseEquipment", b =>
                {
                    b.HasOne("General.DTO.Entities.GameData.EquipmentType", "equipmentType")
                        .WithMany()
                        .HasForeignKey("equipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("base_equipments__equipment_type_id__equipment_types__fkey");

                    b.HasOne("General.DTO.Entities.GameData.SmithingMaterial", "smithingMaterial")
                        .WithMany()
                        .HasForeignKey("smithingMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("base_equipments__smithing_material_id__smithing_materials__fkey");

                    b.Navigation("equipmentType");

                    b.Navigation("smithingMaterial");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.EquipmentType", b =>
                {
                    b.HasOne("General.DTO.Entities.GameData.SlotType", "slotType")
                        .WithMany()
                        .HasForeignKey("slotTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("equipment_types__slot_type_id__slot_types__fkey");

                    b.Navigation("slotType");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.MaterialDamagePercent", b =>
                {
                    b.HasOne("General.DTO.Entities.GameData.DamageType", "damageType")
                        .WithMany()
                        .HasForeignKey("damageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("material_damage_percents__damage_type_id__damage_types__fkey");

                    b.HasOne("General.DTO.Entities.GameData.SmithingMaterial", "smithingMaterials")
                        .WithMany()
                        .HasForeignKey("smithingMaterialsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("material_damage_percents__smithing_materials_id__smithing_materials__fkey");

                    b.Navigation("damageType");

                    b.Navigation("smithingMaterials");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.Slot", b =>
                {
                    b.HasOne("General.DTO.Entities.GameData.SlotType", "slotType")
                        .WithMany()
                        .HasForeignKey("slotTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("slots__slot_type_id__slot_types__fkey");

                    b.Navigation("slotType");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.X_BaseHero_Ability", b =>
                {
                    b.HasOne("General.DTO.Entities.GameData.Ability", "ability")
                        .WithMany()
                        .HasForeignKey("abilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("x_base_heroes_abilities__ability_id__abilities__fkey");

                    b.HasOne("General.DTO.Entities.GameData.BaseHero", "baseHero")
                        .WithMany()
                        .HasForeignKey("baseHeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("x_base_heroes_abilities__base_hero_id__base_heroes__fkey");

                    b.Navigation("ability");

                    b.Navigation("baseHero");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.X_Battlefield_BaseHero", b =>
                {
                    b.HasOne("General.DTO.Entities.GameData.BaseHero", "baseHero")
                        .WithMany()
                        .HasForeignKey("baseHeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("x_battlefields_base_heroes__base_hero_id__base_heroes__fkey");

                    b.HasOne("General.DTO.Entities.GameData.Battlefield", "battlefield")
                        .WithMany()
                        .HasForeignKey("battlefieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("x_battlefields_base_heroes__battlefield_id__battlefields__fkey");

                    b.Navigation("baseHero");

                    b.Navigation("battlefield");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.X_EquipmentType_DamageType", b =>
                {
                    b.HasOne("General.DTO.Entities.GameData.DamageType", "damageType")
                        .WithMany()
                        .HasForeignKey("damageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("x_equipment_types_damage_types__damage_type_id__damage_types__fkey");

                    b.HasOne("General.DTO.Entities.GameData.EquipmentType", "equipmentType")
                        .WithMany()
                        .HasForeignKey("equipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("x_equipment_types_damage_types__equipment_type_id__equipment_types__fkey");

                    b.Navigation("damageType");

                    b.Navigation("equipmentType");
                });

            modelBuilder.Entity("General.DTO.Entities.GameData.X_Hero_CreatureType", b =>
                {
                    b.HasOne("General.DTO.Entities.GameData.BaseHero", "baseHero")
                        .WithMany()
                        .HasForeignKey("baseHeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("x_heroes_creature_types__base_hero_id__base_heroes__fkey");

                    b.HasOne("General.DTO.Entities.GameData.CreatureType", "creatureType")
                        .WithMany()
                        .HasForeignKey("creatureTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("x_heroes_creature_types__creature_type_id__creature_types__fkey");

                    b.Navigation("baseHero");

                    b.Navigation("creatureType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("identity_role_claims__role_id__identity_roles__fkey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("identity_user_claims__user_id__identity_users__fkey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("identity_user_logins__user_id__identity_users__fkey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("identity_user_roles__role_id__identity_roles__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("identity_user_roles__user_id__identity_users__fkey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("identity_user_tokens__user_id__identity_users__fkey");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Collection.DropRate", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("drop_rates__user_id__identity_users__fkey");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Logs.AuthenticationLog", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.UserDevice", "userDevice")
                        .WithMany()
                        .HasForeignKey("userDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("authentication_logs__user_device_id__user_devices__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("authentication_logs__user_id__identity_users__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.UserSession", "userSession")
                        .WithMany()
                        .HasForeignKey("userSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("authentication_logs__user_session_id__user_sessions__fkey");

                    b.Navigation("user");

                    b.Navigation("userDevice");

                    b.Navigation("userSession");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Logs.RegistrationLog", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.UserDevice", "userDevice")
                        .WithMany()
                        .HasForeignKey("userDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("registration_logs__user_device_id__user_devices__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("registration_logs__user_id__identity_users__fkey");

                    b.Navigation("user");

                    b.Navigation("userDevice");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserAccesskey", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_accesskeys__user_id__identity_users__fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserBan", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Server.UserBanReason", "UserBanReason")
                        .WithMany()
                        .HasForeignKey("UserBanReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_bans__user_ban_reason_id__user_ban_reasons__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "User")
                        .WithMany("UserBans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_bans__user_id__identity_users__fkey");

                    b.Navigation("User");

                    b.Navigation("UserBanReason");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserSession", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.UserDevice", "UserDevice")
                        .WithMany()
                        .HasForeignKey("UserDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_sessions__user_device_id__user_devices__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Server.UserSessionInactivationReason", "UserSessionInactivationReason")
                        .WithMany()
                        .HasForeignKey("UserSessionInactivationReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("user_sessions__user_session_inactivation_reason_id__user_session_inactivation_reasons__fkey");

                    b.Navigation("UserDevice");

                    b.Navigation("UserSessionInactivationReason");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.User", b =>
                {
                    b.Navigation("UserBans");
                });
#pragma warning restore 612, 618
        }
    }
}
