// <auto-generated />
using System;
using System.Net;
using General.DTO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server_DB_Postgres;

#nullable disable

namespace Server_DB_Postgres.Migrations
{
    [DbContext(typeof(DbContextGame))]
    [Migration("20260112031013_EasyRefreshTokenRemove")]
    partial class EasyRefreshTokenRemove
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("identity_roles__pkey");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("identity_roles__normalized_name__idx");

                    b.ToTable("identity_roles", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("identity_role_claims__pkey");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("identity_role_claims__role_id__idx");

                    b.ToTable("identity_role_claims", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("identity_user_claims__pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("identity_user_claims__user_id__idx");

                    b.ToTable("identity_user_claims", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("identity_user_logins__pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("identity_user_logins__user_id__idx");

                    b.ToTable("identity_user_logins", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("identity_user_roles__pkey");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("identity_user_roles__role_id__idx");

                    b.ToTable("identity_user_roles", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("identity_user_tokens__pkey");

                    b.ToTable("identity_user_tokens", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Collection.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseEquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("base_equipment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("group_name");

                    b.Property<Guid?>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<int?>("SlotId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("equipments__pkey");

                    b.HasIndex("BaseEquipmentId")
                        .HasDatabaseName("equipments__base_equipment_id__idx");

                    b.HasIndex("HeroId")
                        .HasDatabaseName("equipments__hero_id__idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("equipments__user_id__idx");

                    b.HasIndex("SlotId", "HeroId")
                        .IsUnique()
                        .HasDatabaseName("equipments__slot_id__hero_id__idx");

                    b.ToTable("equipments", "collection");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Collection.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Agility")
                        .HasColumnType("integer")
                        .HasColumnName("agility");

                    b.Property<int>("BaseHeroId")
                        .HasColumnType("integer")
                        .HasColumnName("base_hero_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CritChance")
                        .HasColumnType("integer")
                        .HasColumnName("crit_chance");

                    b.Property<int>("CritPower")
                        .HasColumnType("integer")
                        .HasColumnName("crit_power");

                    b.Property<Dice>("Damage")
                        .HasColumnType("jsonb")
                        .HasColumnName("damage");

                    b.Property<int>("EnduranceMagical")
                        .HasColumnType("integer")
                        .HasColumnName("endurance_magical");

                    b.Property<int>("EndurancePhysical")
                        .HasColumnType("integer")
                        .HasColumnName("endurance_physical");

                    b.Property<long>("ExperienceNow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("experience_now");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("group_name");

                    b.Property<int>("Haste")
                        .HasColumnType("integer")
                        .HasColumnName("haste");

                    b.Property<long>("Health1000")
                        .HasColumnType("bigint")
                        .HasColumnName("health1000");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer")
                        .HasColumnName("intelligence");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<int>("Rarity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("rarity");

                    b.Property<int>("ResistDamageMagical")
                        .HasColumnType("integer")
                        .HasColumnName("resist_damage_magical");

                    b.Property<int>("ResistDamagePhysical")
                        .HasColumnType("integer")
                        .HasColumnName("resist_damage_physical");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Versality")
                        .HasColumnType("integer")
                        .HasColumnName("versality");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("heroes__pkey");

                    b.HasIndex("BaseHeroId")
                        .HasDatabaseName("heroes__base_hero_id__idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("heroes__user_id__idx");

                    b.ToTable("heroes", "collection");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.BaseEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Dice>("Damage")
                        .HasColumnType("jsonb")
                        .HasColumnName("damage");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type_id");

                    b.Property<Dice>("Health")
                        .HasColumnType("jsonb")
                        .HasColumnName("health");

                    b.Property<bool>("IsUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.Property<int?>("SmithingMaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("smithing_material_id");

                    b.HasKey("Id")
                        .HasName("base_equipments__pkey");

                    b.HasIndex("EquipmentTypeId")
                        .HasDatabaseName("base_equipments__equipment_type_id__idx");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("base_equipments__name__idx");

                    b.HasIndex("SmithingMaterialId")
                        .HasDatabaseName("base_equipments__smithing_material_id__idx");

                    b.ToTable("base_equipments", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.BaseHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Dice>("Damage")
                        .HasColumnType("jsonb")
                        .HasColumnName("damage");

                    b.Property<Dice>("Health")
                        .HasColumnType("jsonb")
                        .HasColumnName("health");

                    b.Property<bool>("IsUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique");

                    b.Property<int>("MainStat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("main_stat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.HasKey("Id")
                        .HasName("base_heroes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("base_heroes__name__idx");

                    b.ToTable("base_heroes", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.CreatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("creature_types__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("creature_types__name__idx");

                    b.ToTable("creature_types", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.DamageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("category");

                    b.Property<string>("DevHintRu")
                        .HasColumnType("text")
                        .HasColumnName("dev_hint_ru");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("damage_types__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("damage_types__name__idx");

                    b.ToTable("damage_types", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BlockOtherHand")
                        .HasColumnType("boolean")
                        .HasColumnName("block_other_hand");

                    b.Property<bool>("CanCraftJewelcrafting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_craft_jewelcrafting");

                    b.Property<bool>("CanCraftSmithing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_craft_smithing");

                    b.Property<Dice>("Damage")
                        .HasColumnType("jsonb")
                        .HasColumnName("damage");

                    b.Property<int>("MassMagical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mass_magical");

                    b.Property<int>("MassPhysical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mass_physical");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_ru");

                    b.Property<int>("SlotTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type_id");

                    b.Property<int>("SpendActionPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("spend_action_points");

                    b.HasKey("Id")
                        .HasName("equipment_types__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("equipment_types__name__idx");

                    b.HasIndex("SlotTypeId")
                        .HasDatabaseName("equipment_types__slot_type_id__idx");

                    b.ToTable("equipment_types", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.MaterialDamagePercent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("damage_type_id");

                    b.Property<int>("Percent")
                        .HasColumnType("integer")
                        .HasColumnName("percent");

                    b.Property<int>("SmithingMaterialsId")
                        .HasColumnType("integer")
                        .HasColumnName("smithing_materials_id");

                    b.HasKey("Id")
                        .HasName("material_damage_percents__pkey");

                    b.HasIndex("DamageTypeId")
                        .HasDatabaseName("material_damage_percents__damage_type_id__idx");

                    b.HasIndex("SmithingMaterialsId")
                        .HasDatabaseName("material_damage_percents__smithing_materials_id__idx");

                    b.ToTable("material_damage_percents", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("SlotTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type_id");

                    b.HasKey("Id")
                        .HasName("slots__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("slots__name__idx");

                    b.HasIndex("SlotTypeId")
                        .HasDatabaseName("slots__slot_type_id__idx");

                    b.ToTable("slots", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.SlotType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("slot_types__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("slot_types__name__idx");

                    b.ToTable("slot_types", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.SmithingMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("smithing_materials__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("smithing_materials__name__idx");

                    b.ToTable("smithing_materials", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.X_EquipmentType_DamageType", b =>
                {
                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type_id")
                        .HasColumnOrder(0);

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("damage_type_id")
                        .HasColumnOrder(1);

                    b.Property<int>("DamageCoef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("damage_coef");

                    b.HasKey("EquipmentTypeId", "DamageTypeId")
                        .HasName("x_equipment_type_damage_type__pkey");

                    b.HasIndex("DamageTypeId")
                        .HasDatabaseName("x_equipment_type_damage_type__damage_type_id__idx");

                    b.ToTable("x_equipment_type_damage_type", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.X_Hero_CreatureType", b =>
                {
                    b.Property<int>("BaseHeroId")
                        .HasColumnType("integer")
                        .HasColumnName("base_hero_id")
                        .HasColumnOrder(0);

                    b.Property<int>("CreatureTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_type_id")
                        .HasColumnOrder(1);

                    b.HasKey("BaseHeroId", "CreatureTypeId")
                        .HasName("x_hero_creature_type__pkey");

                    b.HasIndex("CreatureTypeId")
                        .HasDatabaseName("x_hero_creature_type__creature_type_id__idx");

                    b.ToTable("x_hero_creature_type", "game_data");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Logs.AuthRegLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ActionIsAuthentication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("action_is_authentication");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<Guid?>("UserDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_device_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("auth_reg_logs__pkey");

                    b.HasIndex("UserDeviceId")
                        .HasDatabaseName("auth_reg_logs__user_device_id__idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("auth_reg_logs__user_id__idx");

                    b.ToTable("auth_reg_logs", "logs");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Server.UserBanReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("user_ban_reasons__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("user_ban_reasons__name__idx");

                    b.ToTable("user_ban_reasons", "server");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("time_zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("identity_users__pkey");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("identity_users__normalized_email__idx");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("identity_users__normalized_user_name__idx");

                    b.ToTable("identity_users", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserBanReasonId")
                        .HasColumnType("integer")
                        .HasColumnName("user_ban_reason_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("user_bans__pkey");

                    b.HasIndex("UserBanReasonId")
                        .HasDatabaseName("user_bans__user_ban_reason_id__idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("user_bans__user_id__idx");

                    b.ToTable("user_bans", "users");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_model");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_type");

                    b.Property<string>("DeviceUniqueIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_unique_identifier");

                    b.Property<string>("GraphicsDeviceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("graphics_device_name");

                    b.Property<int?>("GraphicsMemorySize")
                        .HasColumnType("integer")
                        .HasColumnName("graphics_memory_size");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operating_system");

                    b.Property<int?>("ProcessorCount")
                        .HasColumnType("integer")
                        .HasColumnName("processor_count");

                    b.Property<string>("ProcessorType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("processor_type");

                    b.Property<string>("SystemEnvironmentUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("system_environment_user_name");

                    b.Property<string>("SystemInfoNpotSupport")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("system_info_npot_support");

                    b.Property<bool?>("SystemInfoSupportsInstancing")
                        .HasColumnType("boolean")
                        .HasColumnName("system_info_supports_instancing");

                    b.Property<int?>("SystemMemorySize")
                        .HasColumnType("integer")
                        .HasColumnName("system_memory_size");

                    b.Property<int?>("TimeZoneMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_zone_minutes");

                    b.HasKey("Id")
                        .HasName("user_devices__pkey");

                    b.ToTable("user_devices", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("identity_role_claims__role_id__identity_roles__fkey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("identity_user_claims__user_id__identity_users__fkey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("identity_user_logins__user_id__identity_users__fkey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("identity_user_roles__role_id__identity_roles__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("identity_user_roles__user_id__identity_users__fkey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("identity_user_tokens__user_id__identity_users__fkey");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Collection.Equipment", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.BaseEquipment", "BaseEquipment")
                        .WithMany()
                        .HasForeignKey("BaseEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("equipments__base_equipment_id__base_equipments__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Collection.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("equipments__hero_id__heroes__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.GameData.Slot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("equipments__slot_id__slots__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("equipments__user_id__identity_users__fkey");

                    b.Navigation("BaseEquipment");

                    b.Navigation("Hero");

                    b.Navigation("Slot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Collection.Hero", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.BaseHero", "BaseHero")
                        .WithMany()
                        .HasForeignKey("BaseHeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("heroes__base_hero_id__base_heroes__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("heroes__user_id__identity_users__fkey");

                    b.Navigation("BaseHero");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.BaseEquipment", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.EquipmentType", "EquipmentTypes")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("base_equipments__equipment_type_id__equipment_types__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.GameData.SmithingMaterial", "SmithingMaterial")
                        .WithMany()
                        .HasForeignKey("SmithingMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("base_equipments__smithing_material_id__smithing_materials__fkey");

                    b.Navigation("EquipmentTypes");

                    b.Navigation("SmithingMaterial");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.EquipmentType", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.SlotType", null)
                        .WithMany("EquipmentTypes")
                        .HasForeignKey("SlotTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("equipment_types__slot_type_id__slot_types__fkey");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.MaterialDamagePercent", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.DamageType", "DamageType")
                        .WithMany()
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("material_damage_percents__damage_type_id__damage_types__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.GameData.SmithingMaterial", "SmithingMaterials")
                        .WithMany("MaterialDamagePercents")
                        .HasForeignKey("SmithingMaterialsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("material_damage_percents__smithing_materials_id__smithing_materials__fkey");

                    b.Navigation("DamageType");

                    b.Navigation("SmithingMaterials");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.Slot", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.SlotType", "SlotType")
                        .WithMany()
                        .HasForeignKey("SlotTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("slots__slot_type_id__slot_types__fkey");

                    b.Navigation("SlotType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.X_EquipmentType_DamageType", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.DamageType", "DamageType")
                        .WithMany("X_EquipmentType_DamageType")
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("x_equipment_type_damage_type__damage_type_id__damage_types__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.GameData.EquipmentType", "EquipmentType")
                        .WithMany("X_EquipmentType_DamageType")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("x_equipment_type_damage_type__equipment_type_id__equipment_types__fkey");

                    b.Navigation("DamageType");

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.X_Hero_CreatureType", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.GameData.BaseHero", "BaseHero")
                        .WithMany("X_Hero_CreatureType")
                        .HasForeignKey("BaseHeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("x_hero_creature_type__base_hero_id__base_heroes__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.GameData.CreatureType", "CreatureType")
                        .WithMany("X_Hero_CreatureType")
                        .HasForeignKey("CreatureTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("x_hero_creature_type__creature_type_id__creature_types__fkey");

                    b.Navigation("BaseHero");

                    b.Navigation("CreatureType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Logs.AuthRegLog", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Users.UserDevice", "UserDevice")
                        .WithMany()
                        .HasForeignKey("UserDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("auth_reg_logs__user_device_id__user_devices__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("auth_reg_logs__user_id__identity_users__fkey");

                    b.Navigation("User");

                    b.Navigation("UserDevice");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.UserBan", b =>
                {
                    b.HasOne("Server_DB_Postgres.Entities.Server.UserBanReason", "UserBanReason")
                        .WithMany("UserBans")
                        .HasForeignKey("UserBanReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_bans__user_ban_reason_id__user_ban_reasons__fkey");

                    b.HasOne("Server_DB_Postgres.Entities.Users.User", "User")
                        .WithMany("UserBans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_bans__user_id__identity_users__fkey");

                    b.Navigation("User");

                    b.Navigation("UserBanReason");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.BaseHero", b =>
                {
                    b.Navigation("X_Hero_CreatureType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.CreatureType", b =>
                {
                    b.Navigation("X_Hero_CreatureType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.DamageType", b =>
                {
                    b.Navigation("X_EquipmentType_DamageType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.EquipmentType", b =>
                {
                    b.Navigation("X_EquipmentType_DamageType");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.SlotType", b =>
                {
                    b.Navigation("EquipmentTypes");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.GameData.SmithingMaterial", b =>
                {
                    b.Navigation("MaterialDamagePercents");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Server.UserBanReason", b =>
                {
                    b.Navigation("UserBans");
                });

            modelBuilder.Entity("Server_DB_Postgres.Entities.Users.User", b =>
                {
                    b.Navigation("UserBans");
                });
#pragma warning restore 612, 618
        }
    }
}
