// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server_DB_Postgres;

#nullable disable

namespace Server_DB_Postgres.Migrations
{
    [DbContext(typeof(DbContext_Game))]
    partial class DbContext_Game03DataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server_DB_Data.Entities.X_Cross.X_EquipmentType_DamageType", b =>
                {
                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("DamageCoef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("DamageCoef");

                    b.HasKey("EquipmentTypeId", "DamageTypeId")
                        .HasName("X_EquipmentType_DamageType__pkey");

                    b.HasIndex("DamageTypeId")
                        .HasDatabaseName("X_EquipmentType_DamageType__DamageTypeId__idx");

                    b.ToTable("X_EquipmentType_DamageType", "x_Cross");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.X_Cross.X_Hero_CreatureType", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("CreatureTypeId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("HeroId", "CreatureTypeId")
                        .HasName("X_Hero_CreatureType__pkey");

                    b.HasIndex("CreatureTypeId")
                        .HasDatabaseName("X_Hero_CreatureType__CreatureTypeId__idx");

                    b.ToTable("X_Hero_CreatureType", "x_Cross");
                });

            modelBuilder.Entity("Server_DB_Data.Entities._Equipment.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("damage");

                    b.Property<bool>("IsUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.Property<int>("WeaponTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("weapon_type_id");

                    b.HasKey("Id")
                        .HasName("Weapons__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("Weapons__Name__idx");

                    b.HasIndex("WeaponTypeId")
                        .HasDatabaseName("Weapons__WeaponTypeId__idx");

                    b.ToTable("Weapons", "_equipment");
                });

            modelBuilder.Entity("Server_DB_Data.Entities._Heroes.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("damage");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("health");

                    b.Property<bool>("IsUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique");

                    b.Property<int>("MainStat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("main_stat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.HasKey("Id")
                        .HasName("Heroes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("Heroes__Name__idx");

                    b.ToTable("Heroes", "_heroes");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.CreatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("CreatureTypes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("CreatureTypes__Name__idx");

                    b.ToTable("CreatureTypes", "__lists");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.DamageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DevHintRu")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("DamageTypes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("DamageTypes__Name__idx");

                    b.ToTable("DamageTypes", "__lists");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attack")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attack");

                    b.Property<bool>("CanCraftJewelcrafting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_craft_jewelcrafting");

                    b.Property<bool>("CanCraftSmithing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_craft_smithing");

                    b.Property<int>("Mass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mass");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.Property<int>("SlotTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type_id");

                    b.Property<int>("SpendActionPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("spend_action_points");

                    b.HasKey("Id")
                        .HasName("EquipmentTypes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("EquipmentTypes__Name__idx");

                    b.HasIndex("SlotTypeId")
                        .HasDatabaseName("EquipmentTypes__SlotTypeId__idx");

                    b.ToTable("EquipmentTypes", "__lists");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.MaterialDamagePercent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("damage_type_id");

                    b.Property<int>("Percent")
                        .HasColumnType("integer")
                        .HasColumnName("percent");

                    b.Property<int>("SmithingMaterialsId")
                        .HasColumnType("integer")
                        .HasColumnName("smithing_materials_id");

                    b.HasKey("Id")
                        .HasName("MaterialDamagePercents__pkey");

                    b.HasIndex("DamageTypeId")
                        .HasDatabaseName("MaterialDamagePercents__DamageTypeId__idx");

                    b.HasIndex("SmithingMaterialsId")
                        .HasDatabaseName("MaterialDamagePercents__SmithingMaterialsId__idx");

                    b.ToTable("MaterialDamagePercents", "__lists");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.SlotType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("SlotTypes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("SlotTypes__Name__idx");

                    b.ToTable("SlotTypes", "__lists");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.SmithingMaterials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("SmithingMaterials__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("SmithingMaterials__Name__idx");

                    b.ToTable("SmithingMaterials", "__lists");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.X_Cross.X_EquipmentType_DamageType", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.__Lists.DamageType", "DamageType")
                        .WithMany("X_EquipmentType_DamageType")
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("X_EquipmentType_DamageType__DamageTypeId__DamageTypes__fkey");

                    b.HasOne("Server_DB_Data.Entities.__Lists.EquipmentType", "EquipmentType")
                        .WithMany("X_EquipmentType_DamageType")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("X_EquipmentType_DamageType__EquipmentTypeId__EquipmentTypes__fkey");

                    b.Navigation("DamageType");

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.X_Cross.X_Hero_CreatureType", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.__Lists.CreatureType", "CreatureTypes")
                        .WithMany("X_Hero_CreatureType")
                        .HasForeignKey("CreatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("X_Hero_CreatureType__CreatureTypeId__CreatureTypes__fkey");

                    b.HasOne("Server_DB_Data.Entities._Heroes.Hero", "Hero")
                        .WithMany("X_Hero_CreatureType")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("X_Hero_CreatureType__HeroId__Heroes__fkey");

                    b.Navigation("CreatureTypes");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Server_DB_Data.Entities._Equipment.Weapon", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.__Lists.EquipmentType", "WeaponTypes")
                        .WithMany()
                        .HasForeignKey("WeaponTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Weapons__WeaponTypeId__EquipmentTypes__fkey");

                    b.Navigation("WeaponTypes");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.EquipmentType", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.__Lists.SlotType", null)
                        .WithMany("EquipmentTypes")
                        .HasForeignKey("SlotTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("EquipmentTypes__SlotTypeId__SlotTypes__fkey");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.MaterialDamagePercent", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.__Lists.DamageType", "DamageType")
                        .WithMany()
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MaterialDamagePercents__DamageTypeId__DamageTypes__fkey");

                    b.HasOne("Server_DB_Data.Entities.__Lists.SmithingMaterials", "SmithingMaterials")
                        .WithMany("MaterialDamagePercent")
                        .HasForeignKey("SmithingMaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MaterialDamagePercents__SmithingMaterialsId__SmithingMaterials__fkey");

                    b.Navigation("DamageType");

                    b.Navigation("SmithingMaterials");
                });

            modelBuilder.Entity("Server_DB_Data.Entities._Heroes.Hero", b =>
                {
                    b.Navigation("X_Hero_CreatureType");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.CreatureType", b =>
                {
                    b.Navigation("X_Hero_CreatureType");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.DamageType", b =>
                {
                    b.Navigation("X_EquipmentType_DamageType");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.EquipmentType", b =>
                {
                    b.Navigation("X_EquipmentType_DamageType");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.SlotType", b =>
                {
                    b.Navigation("EquipmentTypes");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.SmithingMaterials", b =>
                {
                    b.Navigation("MaterialDamagePercent");
                });
#pragma warning restore 612, 618
        }
    }
}
