// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server_DB_Data;

#nullable disable

namespace Server_DB_Data.Migrations
{
    [DbContext(typeof(DbContext_Game03Data))]
    [Migration("20251212074701_Names_Fix1")]
    partial class Names_Fix1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server_DB_Data.Entities.X_Cross.X_EquipmentType_DamageType", b =>
                {
                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("DamageCoef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("DamageCoef");

                    b.HasKey("EquipmentTypeId", "DamageTypeId")
                        .HasName("X_EquipmentType_DamageType__pkey");

                    b.HasIndex("DamageTypeId")
                        .HasDatabaseName("X_EquipmentType_DamageType__DamageTypeId__idx");

                    b.HasIndex("EquipmentTypeId")
                        .HasDatabaseName("X_EquipmentType_DamageType__EquipmentTypeId__idx");

                    b.ToTable("X_EquipmentType_DamageType", "x_Cross");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.X_Cross.X_Hero_CreatureType", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("CreatureTypeId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("HeroId", "CreatureTypeId")
                        .HasName("X_Hero_CreatureType__pkey");

                    b.HasIndex("CreatureTypeId")
                        .HasDatabaseName("X_Hero_CreatureType__CreatureTypeId__idx");

                    b.HasIndex("HeroId")
                        .HasDatabaseName("X_Hero_CreatureType__HeroId__idx");

                    b.ToTable("X_Hero_CreatureType", "x_Cross");
                });

            modelBuilder.Entity("Server_DB_Data.Entities._Equipment.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("damage");

                    b.Property<bool>("IsUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.Property<int>("WeaponTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("weapon_type_id");

                    b.HasKey("Id")
                        .HasName("Weapons__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("Weapons__Name__idx");

                    b.HasIndex("WeaponTypeId")
                        .HasDatabaseName("Weapons__WeaponTypeId__idx");

                    b.ToTable("Weapons", "_equipment");
                });

            modelBuilder.Entity("Server_DB_Data.Entities._Heroes.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("damage");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("health");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unique");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.HasKey("Id")
                        .HasName("Heroes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("Heroes__Name__idx");

                    b.ToTable("Heroes", "_heroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = "4d21_44",
                            Health = "16d24_200",
                            IsUnique = false,
                            Name = "Warrior",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 2,
                            Damage = "5d21_55",
                            Health = "10d28_145",
                            IsUnique = false,
                            Name = "Huntress",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 3,
                            Damage = "3d25_39",
                            Health = "11d39_220",
                            IsUnique = false,
                            Name = "Hammerman",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 4,
                            Damage = "4d23_48",
                            Health = "15d21_165",
                            IsUnique = false,
                            Name = "Rogue",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 5,
                            Damage = "4d21_44",
                            Health = "16d58_472",
                            IsUnique = false,
                            Name = "Battle orc",
                            Rarity = 1
                        });
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.CreatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("CreatureTypes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("CreatureTypes__Name__idx");

                    b.ToTable("CreatureTypes", "__lists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Humanoid"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Orc"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zombie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vampire"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Skeleton"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bear"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Wolf"
                        });
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.DamageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DevHintRu")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("DamageTypes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("DamageTypes__Name__idx");

                    b.ToTable("DamageTypes", "__lists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DevHintRu = "Копьё Пика Рапира Шпага Трезубец Лук Арбалет Дротики Меч(колющий)",
                            Name = "Piercing",
                            NameRu = "Колющий"
                        },
                        new
                        {
                            Id = 2,
                            DevHintRu = "Булава Палица Боевой молот Моргенштерн ",
                            Name = "Blunt",
                            NameRu = "Дробящий"
                        },
                        new
                        {
                            Id = 3,
                            DevHintRu = "Сабля Ятаган Катана Скимитар Боевой веер Коса Бумеранг Чакрам Меч(режущий)",
                            Name = "Cutting",
                            NameRu = "Режущий"
                        },
                        new
                        {
                            Id = 4,
                            DevHintRu = "Топор Секира Бердыш Алебарда",
                            Name = "Chopping",
                            NameRu = "Рубящий"
                        },
                        new
                        {
                            Id = 5,
                            DevHintRu = "\"Проявления: Волшебные стрелы (Magic Missile), телекинетические удары, невидимые клинки силы.\r\n\r\nУязвимы: Призраки, астральные существа (иногда).\r\n\r\nУстойчивы/Иммунны: Практически нет, это магическая энергия.\r\n\r\nОсобенность: Редко имеет сопротивление. Наносит чистый, не-элементальный магический урон. Часто не может быть отражен или заблокирован обычным щитом, только магическими средствами. Может отбрасывать цели.\"",
                            Name = "Force",
                            NameRu = "Силовой"
                        },
                        new
                        {
                            Id = 6,
                            DevHintRu = "\"Проявления: Огненные шары, пламя дракона, горение.\r\n\r\nУязвимы: Духи льда, растения, нежить (часто), насекомые, ледяные элементали.\r\n\r\nУстойчивы/Иммунны: Демоны, огненные элементали, лавовые големы, красные драконы.\r\n\r\nОсобенность: Часто накладывает эффект горения (DoT), может разрушать ледяные преграды, поджигать местность. Противоположен Ледяному.\r\n\r\n\"",
                            Name = "Fire",
                            NameRu = "Огненный"
                        },
                        new
                        {
                            Id = 7,
                            DevHintRu = "\"Проявления: Ледяные стрелы, стужа, обморожение, ледяная тюрьма.\r\n\r\nУязвимы: Огненные существа, драконы, рептилии, лавовые големы.\r\n\r\nУстойчивы/Иммунны: Ледяные элементали, белые драконы, арктические существа.\r\n\r\nОсобенность: Часто накладывает эффект замедления или оковы (обездвиживания). Может создавать ледяной наст на воде. Противоположен Огненному.\"",
                            Name = "Frost",
                            NameRu = "Ледяной"
                        },
                        new
                        {
                            Id = 8,
                            DevHintRu = "\"Проявления: Молнии, электрические разряды, шок, громовые волны.\r\n\r\nУязвимы: Механизмы (роботы, големы), существа в металлической броне, водные/слизневые существа (проводят ток).\r\n\r\nУстойчивы/Иммунны: Воздушные элементали, существа из изоляционных материалов (камень, дерево — не всегда).\r\n\r\nОсобенность: Высокий шанс наложить эффект стана (паралич, оглушение). Урон может цепляться на несколько ближайших целей. Часто игнорирует часть брони.\"",
                            Name = "Electric",
                            NameRu = "Электрический"
                        },
                        new
                        {
                            Id = 9,
                            DevHintRu = "\"Проявления: Ядовитые облака, укусы, отравленные клинки, токсичные выбросы.\r\n\r\nУязвимы: Органические, живые существа (люди, звери, растения).\r\n\r\nУстойчивы/Иммунны: Нежить, конструкты, каменные/земляные элементали, ядовитые сами по себе монстры (гигантские пауки, скорпионы).\r\n\r\nОсобенность:* Практически всегда наносит урон по времени (Damage over Time - DoT). Может накладывать ослабляющие эффекты (снижение характеристик, замедление регенерации).\"",
                            Name = "Poison",
                            NameRu = "Ядовитый"
                        },
                        new
                        {
                            Id = 10,
                            DevHintRu = "\"Проявления: Разрушительный рёв, ударная звуковая волна, резонанс, разрыв барабанных перепонок, крик банши, звуковые пушки.\r\n\r\nУязвимы: Стеклянные/хрустальные существа, конструкции с хрупкими элементами, существа с тонким слухом (летучие мыши, эльфы). Механизмы (может нарушить работу).\r\n\r\nУстойчивы/Иммунны: Глухие существа, каменные/земляные големы (плохо проводят звук), существа из вакуума/космоса, призраки (иногда).\r\n\r\nОсобенность: Часто игнорирует физическую броню (звук проходит сквозь пластины) и магическую защиту. Имеет высокий шанс наложить дебаффы: оглушение, дезориентация, снижение точности, развеивание иллюзий/невидимости. Может активировать хрупкие механизмы или разрушать звуковые барьеры. В тихих локациях (подземелья) может привлекать других врагов.\"",
                            Name = "Sonic",
                            NameRu = "Звуковой"
                        },
                        new
                        {
                            Id = 11,
                            DevHintRu = "\"Проявления: Божественный гнев, очищающий свет, заклинания жрецов и паладинов, освящённое оружие.\r\n\r\nУязвимы: Нежить (зомби, скелеты, призраки, вампиры), демоны/исчадия, существа Тьмы и Хаоса.\r\n\r\nУстойчивы/Иммунны: Ангелы, святые существа, некоторые нейтральные духи природы.\r\n\r\nОсобенность: Часто прерывает концентрацию магов, изгоняет/отпугивает нежить, наносит увеличенный/критический урон к уязвимым типам. Может накладывать ослепление.\"",
                            Name = "Light",
                            NameRu = "Световой"
                        },
                        new
                        {
                            Id = 12,
                            DevHintRu = "\"Проявления: Энергия смерти, вампиризм (кража HP), проклятия, теневая магия.\r\n\r\nУязвимы: Живые существа (подрывает жизненную силу), святые существа (иногда).\r\n\r\nУстойчивы/Иммунны: Нежить (часто её лечит или не вредит), демоны Тени, существа Смерти.\r\n\r\nОсобенность: Может накладывать эффекты снижения максимального запаса здоровья, запрета на лечение (анти-хил), страха или ослабления. Противоположен Священному.\"",
                            Name = "Necrotic",
                            NameRu = "Некротический"
                        },
                        new
                        {
                            Id = 13,
                            DevHintRu = "\"Проявления: Взрыв разума, телепатическое копье, ментальные тиски, навязывание невыносимых мыслей, иллюзии, причиняющие реальную боль, атаки по сновидениям.\r\n\r\nУязвимы: Все разумные существа (люди, эльфы, орки, драконы). Особенно те, кто обладает высоким интеллектом, но слабой силой воли.\r\n\r\nУстойчивы/Иммунны: Конструкты, големы, неразумная нежить (зомби, скелеты), животные/звери с примитивным интеллектом, берсеркеры/дикари (их разум хаотичен и защищен яростью), роботы, некоторые демоны пустоты.\r\n\r\nОсобенность: Почти всегда игнорирует физическую броню и магическую защиту (зависит от сопротивления ментальным эффектам/силе воли). Реже наносит чистый урон, чаще накладывает мощнейшие контроль-эффекты: страх, очарование, сон, паралич, безумие, взятие под контроль. Может снижать характеристики (Интеллект, Мудрость, Харизму). Не оставляет физических ран.\"",
                            Name = "Telepathic",
                            NameRu = "Телепатический"
                        },
                        new
                        {
                            Id = 14,
                            DevHintRu = "\"Проявления: Плевки кислотой, едкие пары, растворяющие жидкости.\r\n\r\nУязвимы: Существа с хитиновым/металлическим панцирем, механизмы, бронированные цели.\r\n\r\nУстойчивы/Иммунны: Слизни, кислотные элементали, аморфные существа.\r\n\r\nОсобенность: Часто снижает защиту (броню) цели на время или игнорирует её часть. Может наносить урон предметам/снаряжению.\"",
                            Name = "Acid",
                            NameRu = "Кислотный"
                        },
                        new
                        {
                            Id = 15,
                            DevHintRu = "\"Проявления: Нестабильная энергия хаоса, смесь стихий, дикая магия.\r\n\r\nУязвимы: Существа Закона и Порядка (дэвы, механикусы).\r\n\r\nУстойчивы/Иммунны: Демоны Бездны, хаотические элементали.\r\n\r\nОсобенность: Часто игнорирует фиксированный процент всех сопротивлений (например, 50% урона проходит всегда) или имеет шанс наложить случайный негативный эффект. Непредсказуем.\"",
                            Name = "Chaos",
                            NameRu = "Хаотический"
                        },
                        new
                        {
                            Id = 16,
                            DevHintRu = "\"Проявления: Божественная кара, нарушение законов реальности, урон из самого \"\"кода\"\" вселенной, абсолютное расщепление материи, хирургически точное уничтожение без эффектов.\r\n\r\nУязвимы: ВСЕ. По определению.\r\n\r\nУстойчивы/Иммунны: НИКТО. По определению. (Хотя могут быть исключения в виде уникальных божественных артефактов или \"сюжетная неуязвимость\").\r\n\r\nОсобенность: Игнорирует ВСЕ виды защиты, сопротивления, иммунитеты, поглощения и снижения урона. Наносит ровно то количество урона, которое указано. Это последний аргумент в игровом балансе. Крайне редок, обычно доступен через:\r\n\r\nУльтимативные способности с долгим откатом.\r\n\r\nЛегендарные/божественные артефакты.\r\n\r\nСпособности, срабатывающие при выполнении сложных условий (например, при HP противника ниже 5%).\r\n\r\nКак механика для определенных типов врагов (например, урон от падения в бездну или \"\"неизбежная\"\" атака босса).\"",
                            Name = "Pure",
                            NameRu = "Чистый"
                        });
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attack")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attack");

                    b.Property<bool>("CanCraftJewelcrafting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_craft_jewelcrafting");

                    b.Property<bool>("CanCraftSmithing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_craft_smithing");

                    b.Property<int>("Mass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mass");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.Property<int>("SlotTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type_id");

                    b.Property<string>("SpendActionPoints")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("spend_action_points");

                    b.HasKey("Id")
                        .HasName("EquipmentTypes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("EquipmentTypes__Name__idx");

                    b.HasIndex("SlotTypeId")
                        .HasDatabaseName("EquipmentTypes__SlotTypeId__idx");

                    b.ToTable("EquipmentTypes", "__lists");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.MaterialDamagePercent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("damage_type_id");

                    b.Property<int>("Percent")
                        .HasColumnType("integer")
                        .HasColumnName("percent");

                    b.Property<int>("SmithingMaterialsId")
                        .HasColumnType("integer")
                        .HasColumnName("smithing_materials_id");

                    b.HasKey("Id")
                        .HasName("MaterialDamagePercents__pkey");

                    b.HasIndex("DamageTypeId")
                        .HasDatabaseName("MaterialDamagePercents__DamageTypeId__idx");

                    b.HasIndex("SmithingMaterialsId")
                        .HasDatabaseName("MaterialDamagePercents__SmithingMaterialsId__idx");

                    b.ToTable("MaterialDamagePercents", "__lists");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.SlotType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("SlotTypes__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("SlotTypes__Name__idx");

                    b.ToTable("SlotTypes", "__lists");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.SmithingMaterials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru");

                    b.HasKey("Id")
                        .HasName("SmithingMaterials__pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("SmithingMaterials__Name__idx");

                    b.ToTable("SmithingMaterials", "__lists");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.X_Cross.X_EquipmentType_DamageType", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.__Lists.DamageType", "DamageType")
                        .WithMany("X_EquipmentType_DamageType")
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("X_EquipmentType_DamageType__DamageTypeId__DamageTypes__fkey");

                    b.HasOne("Server_DB_Data.Entities.__Lists.EquipmentType", "EquipmentType")
                        .WithMany("X_EquipmentType_DamageType")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("X_EquipmentType_DamageType__EquipmentTypeId__EquipmentTypes__fkey");

                    b.Navigation("DamageType");

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.X_Cross.X_Hero_CreatureType", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.__Lists.CreatureType", "CreatureTypes")
                        .WithMany("X_Hero_CreatureType")
                        .HasForeignKey("CreatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("X_Hero_CreatureType__CreatureTypeId__CreatureTypes__fkey");

                    b.HasOne("Server_DB_Data.Entities._Heroes.Hero", "Hero")
                        .WithMany("X_Hero_CreatureType")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("X_Hero_CreatureType__HeroId__Heroes__fkey");

                    b.Navigation("CreatureTypes");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Server_DB_Data.Entities._Equipment.Weapon", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.__Lists.EquipmentType", "WeaponTypes")
                        .WithMany()
                        .HasForeignKey("WeaponTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Weapons__WeaponTypeId__EquipmentTypes__fkey");

                    b.Navigation("WeaponTypes");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.EquipmentType", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.__Lists.SlotType", null)
                        .WithMany("EquipmentTypes")
                        .HasForeignKey("SlotTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("EquipmentTypes__SlotTypeId__SlotTypes__fkey");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.MaterialDamagePercent", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.__Lists.DamageType", "DamageType")
                        .WithMany()
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MaterialDamagePercents__DamageTypeId__DamageTypes__fkey");

                    b.HasOne("Server_DB_Data.Entities.__Lists.SmithingMaterials", "SmithingMaterials")
                        .WithMany("MaterialDamagePercent")
                        .HasForeignKey("SmithingMaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MaterialDamagePercents__SmithingMaterialsId__SmithingMaterials__fkey");

                    b.Navigation("DamageType");

                    b.Navigation("SmithingMaterials");
                });

            modelBuilder.Entity("Server_DB_Data.Entities._Heroes.Hero", b =>
                {
                    b.Navigation("X_Hero_CreatureType");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.CreatureType", b =>
                {
                    b.Navigation("X_Hero_CreatureType");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.DamageType", b =>
                {
                    b.Navigation("X_EquipmentType_DamageType");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.EquipmentType", b =>
                {
                    b.Navigation("X_EquipmentType_DamageType");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.SlotType", b =>
                {
                    b.Navigation("EquipmentTypes");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.SmithingMaterials", b =>
                {
                    b.Navigation("MaterialDamagePercent");
                });
#pragma warning restore 612, 618
        }
    }
}
