using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Server_DB_Data.Migrations
{
    /// <inheritdoc />
    public partial class ТипУронаIdInt2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Создаем временный int столбец
            migrationBuilder.AddColumn<int>(
                name: "id_new",
                schema: "_main",
                table: "type_damage",
                type: "integer",
                nullable: false);

            // 2. Заполняем его значениями (например, создаем последовательность)
            migrationBuilder.Sql(@"
        CREATE SEQUENCE IF NOT EXISTS _main.type_damage_id_seq;
        UPDATE _main.type_damage 
        SET id_new = nextval('_main.type_damage_id_seq');
    ");

            // 3. Удаляем старый столбец
            migrationBuilder.DropColumn(
                name: "id",
                schema: "_main",
                table: "type_damage");

            // 4. Переименовываем новый столбец
            migrationBuilder.RenameColumn(
                name: "id_new",
                schema: "_main",
                table: "type_damage",
                newName: "id");

            // 5. Делаем его первичным ключом с автоинкрементом
            migrationBuilder.Sql(@"
        ALTER TABLE _main.type_damage 
        ALTER COLUMN id SET NOT NULL,
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY,
        ADD PRIMARY KEY (id);
    ");

            // 6. Обновляем внешние ключи в других таблицах
            // Нужно также обновить sword._type_damage_id
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<Guid>(
                name: "id",
                schema: "_main",
                table: "type_damage",
                type: "uuid",
                nullable: false,
                defaultValueSql: "gen_random_uuid()",
                oldClrType: typeof(int),
                oldType: "integer")
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
        }
    }
}
