// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server_DB_Data;

#nullable disable

namespace Server_DB_Data.Migrations
{
#pragma warning disable
    [DbContext(typeof(DbContext_Game03Data))]
    partial class DbContext_Game03DataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server_DB_Data.Entities.CreatureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("creature_types_pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("creature_types_name_idx");

                    b.ToTable("creature_types", "_main");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<float>("BaseAttack")
                        .HasColumnType("real")
                        .HasColumnName("base_attack");

                    b.Property<float>("BaseHealth")
                        .HasColumnType("real")
                        .HasColumnName("base_health");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("heroes_pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("heroes_name_idx");

                    b.ToTable("heroes", "_main");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.HeroCreatureType", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<Guid>("CreatureTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("HeroId", "CreatureTypeId")
                        .HasName("x_hero_creature_type_pkey");

                    b.HasIndex("CreatureTypeId")
                        .HasDatabaseName("x_hero_creature_type_creature_type_id_idx");

                    b.HasIndex("HeroId")
                        .HasDatabaseName("x_hero_creature_type_hero_id_idx");

                    b.ToTable("x_hero_creature_type", "xcross");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.HeroCreatureType", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.CreatureType", "CreatureType")
                        .WithMany("Heroes")
                        .HasForeignKey("CreatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("x_hero_creature_type_creature_type_id_creature_types_fkey");

                    b.HasOne("Server_DB_Data.Entities.Hero", "Hero")
                        .WithMany("CreatureTypes")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("x_hero_creature_type_hero_id_heroes_fkey");

                    b.Navigation("CreatureType");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.CreatureType", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.Hero", b =>
                {
                    b.Navigation("CreatureTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
