// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server_DB_Data;

#nullable disable

namespace Server_DB_Data.Migrations
{
    [DbContext(typeof(DbContext_Game03Data))]
    partial class DbContext_Game03DataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server_DB_Data.Entities.Directory.CreatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("creature_types_pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("creature_types_name_idx");

                    b.ToTable("creature_types", "__lists");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.X_Cross.X_HeroCreatureType", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("integer")
                        .HasColumnName("hero_id")
                        .HasColumnOrder(0);

                    b.Property<int>("CreatureTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_type_id")
                        .HasColumnOrder(1);

                    b.HasKey("HeroId", "CreatureTypeId")
                        .HasName("x_hero_creature_type_pkey");

                    b.HasIndex("CreatureTypeId")
                        .HasDatabaseName("x_hero_creature_type_creature_type_id_idx");

                    b.HasIndex("HeroId")
                        .HasDatabaseName("x_hero_creature_type_hero_id_idx");

                    b.ToTable("x_hero_creature_type", "x_cross");
                });

            modelBuilder.Entity("Server_DB_Data.Entities._Equipment.Sword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("damage");

                    b.Property<bool>("IsUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unique");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.Property<int>("TypeDamageId")
                        .HasColumnType("integer")
                        .HasColumnName("type_damage_id");

                    b.HasKey("Id")
                        .HasName("sword_pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("sword_name_idx");

                    b.HasIndex("TypeDamageId")
                        .HasDatabaseName("sword_type_damage_id_idx");

                    b.ToTable("sword", "_equipment");
                });

            modelBuilder.Entity("Server_DB_Data.Entities._Heroes.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("damage");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("health");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unique");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.HasKey("Id")
                        .HasName("heroes_pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("heroes_name_idx");

                    b.ToTable("heroes", "_heroes");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.__Lists.TypeDamage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("types_damage_pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("types_damage_name_idx");

                    b.ToTable("types_damage", "__lists");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.X_Cross.X_HeroCreatureType", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.Directory.CreatureType", "CreatureType")
                        .WithMany("Heroes")
                        .HasForeignKey("CreatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("x_hero_creature_type_creature_type_id_creature_types_fkey");

                    b.HasOne("Server_DB_Data.Entities._Heroes.Hero", "Hero")
                        .WithMany("CreatureTypes")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("x_hero_creature_type_hero_id_heroes_fkey");

                    b.Navigation("CreatureType");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Server_DB_Data.Entities._Equipment.Sword", b =>
                {
                    b.HasOne("Server_DB_Data.Entities.__Lists.TypeDamage", "TypeDamage")
                        .WithMany()
                        .HasForeignKey("TypeDamageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sword_type_damage_id_types_damage_fkey");

                    b.Navigation("TypeDamage");
                });

            modelBuilder.Entity("Server_DB_Data.Entities.Directory.CreatureType", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Server_DB_Data.Entities._Heroes.Hero", b =>
                {
                    b.Navigation("CreatureTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
