// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.DB.Data;

#nullable disable

namespace Server.DB.Data.Migrations
{
    [DbContext(typeof(DbContext_Game03Data))]
    [Migration("20250914064646_NewBaseStat001")]
    partial class NewBaseStat001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.DB.Data.Entities.CreatureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_creature_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_creature_types_name");

                    b.ToTable("creature_types", "main");
                });

            modelBuilder.Entity("Server.DB.Data.Entities.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<float>("BaseHealth")
                        .HasColumnType("real")
                        .HasColumnName("base_health");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("_rarity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_heroes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_heroes_name");

                    b.ToTable("heroes", "main");
                });

            modelBuilder.Entity("Server.DB.Data.Entities.HeroCreatureType", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<Guid>("CreatureTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("HeroId", "CreatureTypeId")
                        .HasName("pk_hero_x_creature_type");

                    b.HasIndex("CreatureTypeId")
                        .HasDatabaseName("idx_hero_x_creature_type_creature_type_id");

                    b.HasIndex("HeroId")
                        .HasDatabaseName("idx_hero_x_creature_type_hero_id");

                    b.ToTable("hero_x_creature_type", "relations");
                });

            modelBuilder.Entity("Server.DB.Data.Entities.HeroCreatureType", b =>
                {
                    b.HasOne("Server.DB.Data.Entities.CreatureType", "CreatureType")
                        .WithMany("Heroes")
                        .HasForeignKey("CreatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hero_x_creature_type_creature_type_id_creature_types");

                    b.HasOne("Server.DB.Data.Entities.Hero", "Hero")
                        .WithMany("CreatureTypes")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hero_x_creature_type_hero_id_heroes");

                    b.Navigation("CreatureType");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Server.DB.Data.Entities.CreatureType", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Server.DB.Data.Entities.Hero", b =>
                {
                    b.Navigation("CreatureTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
