// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.DB.Data;

#nullable disable

namespace Server.DB.Data.Migrations
{
    [DbContext(typeof(DbContext_Game03Data))]
    [Migration("20250731045552_Hero_CreatureType_ManyToMany_And_ToSnakeCase")]
    partial class Hero_CreatureType_ManyToMany_And_ToSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreatureTypeHero", b =>
                {
                    b.Property<Guid>("CreatureTypesId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_types_id");

                    b.Property<Guid>("HeroesId")
                        .HasColumnType("uuid")
                        .HasColumnName("heroes_id");

                    b.HasKey("CreatureTypesId", "HeroesId")
                        .HasName("pk_hero_creature_type");

                    b.HasIndex("HeroesId")
                        .HasDatabaseName("idx_hero_creature_type_heroes_id");

                    b.ToTable("hero_creature_type", (string)null);
                });

            modelBuilder.Entity("Server.DB.Data.Entities.CreatureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_creature_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_creature_types_name");

                    b.ToTable("creature_types", (string)null);
                });

            modelBuilder.Entity("Server.DB.Data.Entities.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_heroes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_heroes_name");

                    b.ToTable("heroes", (string)null);
                });

            modelBuilder.Entity("CreatureTypeHero", b =>
                {
                    b.HasOne("Server.DB.Data.Entities.CreatureType", null)
                        .WithMany()
                        .HasForeignKey("CreatureTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hero_creature_type_creature_types_id_creature_types");

                    b.HasOne("Server.DB.Data.Entities.Hero", null)
                        .WithMany()
                        .HasForeignKey("HeroesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hero_creature_type_heroes_id_heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
